services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sampledb
    ports:
      - "43544:5432"
    volumes:
      - postgres_data:/home/nabutabu/programs/crane-oss/postgres_data

volumes:
  postgres_data:
